version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_creditos
    environment:
      POSTGRES_DB: creditosdb
      POSTGRES_USER: creditosuser
      POSTGRES_PASSWORD: creditospassword
    ports:
      - "5432:5432"
    networks:
      - desafio-network

  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka_creditos
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    networks:
      - desafio-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_creditos
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - desafio-network

  backend:
    build:
      context: ./backend
    container_name: backend_creditos
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    networks:
      - desafio-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend_creditos
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - desafio-network

networks:
  desafio-network:
