spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditosdb
    username: creditosuser
    password: creditospassword
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
